# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

#a trigger can be set for a specific branch or file.
#trigger:
pr:
  branches:
    include:
    - main
  paths:
    include:
    - demos/RockPaperScissorsMvc

# a resource on which you will build your app
pool:
  vmImage: 'windows-latest'

#variables that you can access during the build
variables:
  solution: 'demos/RockPaperScissorsMvc/RockPaperScissorsMvc/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

- task: UseDotNet@2
  displayName: 'Installing .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

#testing goes here

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(solution))'
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Project-3-Training(e37a1117-750a-4552-bb20-e84ed6f3c85d)'
    appType: 'webApp'
    WebAppName: '06012021BatchRpsGame'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

# - stage:
#   displayName: Stage1
#   dependsOn: []
#   jobs:
#     - job:
#       steps:
#       - script: echo this is stage 1 The buildCongiuration is $(buildConfiguration).
#     - job:
#       steps:
#       - script: echo this is the second job for the first stage

# - stage: stagesName
#   displayName: Stage2
#   dependsOn: []
#   jobs:
#   - job:
#     steps:
#     - script: echo this is stage2

# - stage:
#   displayName: Stage3
#   dependsOn: []
#   jobs:
#   - job:
#     steps:
#     - script: echo this is stage3
#   - job:
#     steps:
#     - script: echo this is the last job of the last stage

